branch-defaults:
  master:
    environment: mrcesar-dev
global:
  application_name: mrcesar
  default_ec2_keyname: mrcesar-key
  default_platform: Python 3.4
  default_region: us-west-2
  profile: cesar
  sc: git
